services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "27182:27182"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - CORS_ORIGINS=https://192.168.1.15:5173,https://localhost:5173,https://frontend:5173
      - CORS_ALLOW_HEADERS=Content-Type,Authorization,Accept,Origin,X-Requested-With
      - CORS_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS,HEAD,PATCH
      - CORS_ALLOW_CREDENTIALS=true
    volumes:
      - ./backend/database:/app/database
      - ./backend/backend/uploads:/app/backend/uploads
      - ./backend/backend/backups:/app/backend/backups
    networks:
      - whole-home-inventory-system-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./certs:/root/certs:rw
    environment:
      - NODE_ENV=development
      - VITE_API_URL=
      - CERT_OUTPUT_DIR=/root/certs
    depends_on:
      - backend
    networks:
      - whole-home-inventory-system-network

networks:
  whole-home-inventory-system-network:
    driver: bridge