services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "27182:27182"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - CORS_ORIGINS=http://192.168.1.122:5173
    volumes:
      - /volume1/docker/whole-home-inventory-system/database:/app/database
      - /volume1/docker/whole-home-inventory-system/uploads:/app/backend/uploads
      - /volume1/docker/whole-home-inventory-system/backups:/app/backend/backups
    networks:
      - whole-home-inventory-system-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - whole-home-inventory-system-network
    restart: unless-stopped

networks:
  whole-home-inventory-system-network:
    driver: bridge
