services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "27182:27182"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - CORS_ORIGINS=http://192.168.1.122:5173
    volumes:
      - /volume1/docker/whis/database:/app/database
      - /volume1/docker/whis/uploads:/app/backend/uploads
      - /volume1/docker/whis/backups:/app/backend/backups
    networks:
      - whis-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - whis-network
    restart: unless-stopped

networks:
  whis-network:
    driver: bridge