/**
 * Shorthand re-exports of the OpenAPI-generated schemas (v3.0 Part G).
 *
 * The canonical types live in ``./openapi.d.ts`` under
 * ``components['schemas']``. That file is regenerated by
 * ``npm run codegen:api`` from the backend's ``app.openapi()`` dump.
 *
 * Call sites import from here (``import type { Item } from '../api/types'``)
 * so the deep ``components['schemas']['X']`` paths stay contained in one
 * place — if openapi-typescript ever changes its output shape, only this
 * file needs to follow.
 */

import type { components } from './openapi';

type Schemas = components['schemas'];

// --- Users & auth -----------------------------------------------------------
export type User = Schemas['User'];
export type UserCreate = Schemas['UserCreate'];
export type Token = Schemas['Token'];

// --- Items ------------------------------------------------------------------
export type Item = Schemas['Item'];
export type ItemCreate = Schemas['ItemCreate'];
export type ItemUpdate = Schemas['ItemUpdate'];
export type ItemList = Schemas['ItemList'];
export type ItemImage = Schemas['ItemImage'];
export type BulkDeleteRequest = Schemas['BulkDeleteRequest'];
export type ImportResult = Schemas['ImportResult'];
export type CustomFieldsSchema = Schemas['CustomFieldsSchema'];

// --- Backups ----------------------------------------------------------------
export type Backup = Schemas['Backup'];
export type BackupList = Schemas['BackupList'];
export type RestoreRequest = Schemas['RestoreRequest'];
export type RestoreResponse = Schemas['RestoreResponse'];

// --- Jobs (v3.0) ------------------------------------------------------------
export type JobStatus = Schemas['JobStatus'];
export type JobDetail = Schemas['JobDetail'];
export type JobReference = Schemas['JobReference'];

// --- eBay -------------------------------------------------------------------
export type EbayFields = Schemas['EbayFields'];
export type EbayCategory = Schemas['EbayCategory'];
export type EbayCategoryResponse = Schemas['EbayCategoryResponse'];
export type EbayExportRequest = Schemas['EbayExportRequest'];
export type EbayCondition = Schemas['EbayCondition'];
export type EbayDuration = Schemas['EbayDuration'];
export type EbayListingFormat = Schemas['EbayListingFormat'];
export type EbayPaymentMethod = Schemas['EbayPaymentMethod'];
export type EbayReturnPeriod = Schemas['EbayReturnPeriod'];
export type EbayShippingService = Schemas['EbayShippingService'];

// --- Facebook ---------------------------------------------------------------
// Canonical name is FbFields (matching the backend schema). Historical
// aliases (FbFieldsData) existed in v2.3-era hand-written types; if any
// call site still references them, it needs to migrate.
export type FbFields = Schemas['FbFields'];
export type FbCondition = Schemas['FbCondition'];
export type FbAvailability = Schemas['FbAvailability'];
export type FbCopyPasteBlock = Schemas['FbCopyPasteBlock'];
export type FbCatalogExportRequest = Schemas['FbCatalogExportRequest'];

// --- Errors -----------------------------------------------------------------
export type HTTPValidationError = Schemas['HTTPValidationError'];
export type ValidationError = Schemas['ValidationError'];

// ---------------------------------------------------------------------------
// Backend-compat aliases — the hand-written v2.x types used different
// names for a handful of schemas. Keep the aliases here so the rest of
// the v3.0 swap is a mechanical find/replace; downstream code can
// migrate to the canonical names at its own pace.
// ---------------------------------------------------------------------------
export type ItemListResponse = ItemList;
export type RestoreResult = RestoreResponse;
/** v3.0 rename. Old callers referenced FbFieldsData; the backend schema
 *  has always been FbFields. New code should use FbFields directly. */
export type FbFieldsData = FbFields;

// SearchFilter is consumed as query params by the list endpoint, so it
// doesn't appear in the OpenAPI `components/schemas` section. Keep it
// as a hand-written interface that mirrors the backend Pydantic model
// in ``app/schemas.py``.
export interface SearchFilters {
  query?: string;
  category?: string;
  location?: string;
  min_value?: number;
  max_value?: number;
  sort_by?: string;
  sort_desc?: boolean;
  page?: number;
  page_size?: number;
}
// Backward-compat alias — the backend class is named ``SearchFilter``
// (singular). The frontend always used ``SearchFilters`` (plural).
export type SearchFilter = SearchFilters;

// ---------------------------------------------------------------------------
// Frontend-only types (not emitted from the backend OpenAPI schema).
//
// These are either form-input shapes (the backend accepts
// OAuth2PasswordRequestForm which doesn't round-trip as JSON), or
// analytics response shapes where the endpoint still returns a plain
// dict instead of a Pydantic response_model. Migrating the analytics
// endpoints to typed response models is tracked as v3.1 cleanup.
// ---------------------------------------------------------------------------

export interface LoginCredentials {
  username: string;
  password: string;
}

export interface RegisterData {
  email: string;
  username: string;
  password: string;
}

export interface AuthResponse {
  access_token: string;
  token_type: string;
}

// --- Analytics (untyped on the backend today) ------------------------------
export interface ValueByCategory {
  category: string;
  item_count: number;
  total_value: number;
}

export interface ValueByLocation {
  location: string;
  item_count: number;
  total_value: number;
}

export interface ValueTrends {
  total_purchase_value: number;
  total_current_value: number;
  value_change: number;
  value_change_percentage: number;
}

export interface WarrantyItem {
  id: string;
  name: string;
  expiration_date: string;
}

export interface WarrantyStatus {
  expiring_soon: WarrantyItem[];
  expired: WarrantyItem[];
  active: WarrantyItem[];
}

export interface AgeBucket {
  count: number;
  total_value: number;
  items: Array<{
    id: string;
    name: string;
    purchase_date: string;
    current_value: number;
  }>;
}

export type AgeAnalysis = Record<string, AgeBucket>;

// --- eBay extras (not in OpenAPI today) ------------------------------------
export interface EbayExportResponse {
  success: boolean;
  file_url?: string;
  message: string;
  errors?: string[];
  items_processed: number;
}

// --- Facebook extras -------------------------------------------------------
export interface FbCategoriesResponse {
  categories: string[];
}
